apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: testfrontend
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: testfrontend
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
        tier: testfrontend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google-samples/gb-frontend:v4
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below:
          # value: env
        ports:
        - containerPort: 80    
        volumeMounts:
          - mountPath: /test-pd
            name: demovolume
      volumes:
      - name: demovolume
        # This GCE PD must already exist.
        gcePersistentDisk:
          pdName:  demodisk
          fsType: ext4
        
