apiVersion: v1
kind: PersistentVolume
metadata:
  name: demostorageps
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: demostorage
    fsType: ext4