apiVersion: v1
kind: PersistentVolume
metadata:
  name: demostorageps
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /local-pv