apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: democlaim
  labels:
    app: guestbook
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 2Gi