apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: hello-world
    name: test-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    # This GCE PD must already exist.
    gcePersistentDisk:
      pdName:  demodisk
      fsType: ext4
